---
name: 🚀 Spécifier une évolution
description: Renseigner les informations nécessaires pour créer ou améliorer une fonctionnalité pour cartes.gouv.fr
labels: ["enhancement"]
projects: ["IGNF/14"]
type: "Feature"
body:
  - type: textarea
    id: job-to-be-done
    attributes:
      label: 📝 Job to be done (JTBD)
      description: |
        Décrivez la tâche générique que l'utilisateur cherche à accomplir, indépendamment de l'outil.
      placeholder: |
        exemple : Rechercher une donnée par son nom technique afin de consulter les informations la concernant
  - type: textarea
    id: user-story
    attributes:
      label: 🎯 User Story
      description: |
        Décrivez précisément le comportement de la nouvelle fonctionnalité.
      placeholder: |
        - En tant que [type d'utilisateur / persona]
        - Je veux [action concrète à réaliser]
        - Afin de [valeur attendue / bénéfice]
    validations:
      required: true
  - type: textarea
    id: design
    attributes:
      label: 🎨 Design
      description: |
        Décrivez les éléments de design nécéssaire au développement de la fonctionnalité.
      placeholder: |
        - Composition
        - Comportement
        - Contenus
        - Emplacement
        - Points de rupture
  - type: textarea
    id: criteres-d-acceptation
    attributes:
      label: ✅ Critères d'acceptation
      description: >
        Décrivez les conditions observables qui permettent d'identifier la bonne mise en place de l'US.
      placeholder: |
        - [ ] Exemple : Barre de recherche visible et cliquable
        - [ ] Exemple : Options de recherche avancée disponibles
        - [ ] Exemple : Propositions de résultat au fur et à mesure de l'écriture
    validations:
      required: true
  - type: textarea
    id: liens
    attributes:
      label: 🔗 Liens
      description: |
        Renseignez les liens utiles à l'évolution.
      placeholder: |
        - Maquette figma : [lien]
        - Données de test : [lien]
        - Documentation annexe : [lien]
  - type: textarea
    id: impact-attendu
    attributes:
      label: 📊 impact attendu
      description: >
        Décrivez quelle valeur cela apporte-t-il à l'utilisateur, et
        comment le mesurer.
      placeholder: >
        - Valeur utilisateur : [Exemple : Faciliter la recherche de donnée => l'agent gagne du temps et fiabilise ses résultats]
        - Mesure : [Exemple : nombre de recherches par nom technique]
  - type: textarea
    id: additional-context
    attributes:
      label: 🔧 Autres éléments de contexte
      description: |
        À remplir par l'équipe technique pour s'assurer que l'US est réalisable.
